/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_molei_ipclient4droid_IPClient */

#ifndef _Included_com_molei_ipclient4droid_IPClient
#define _Included_com_molei_ipclient4droid_IPClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_molei_ipclient4droid_IPClient
 * Method:    Send05
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_molei_ipclient4droid_IPClient_Send05
  (JNIEnv *, jobject);

/*
 * Class:     com_molei_ipclient4droid_IPClient
 * Method:    Send1F
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_molei_ipclient4droid_IPClient_Send1F
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_molei_ipclient4droid_IPClient
 * Method:    Send21
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_molei_ipclient4droid_IPClient_Send21
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

/*
 * Class:     com_molei_ipclient4droid_IPClient
 * Method:    Send_1e
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_molei_ipclient4droid_IPClient_Send_11e
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
